---
all:
  hosts:
    jenkins-master-01:
      ansible_host: 62.84.125.153
      ansible_ssh_private_key_file: /home/vagrant/.ssh/id_rsa
    
    jenkins-agent-01:
      ansible_host: 84.252.131.2
      ansible_ssh_private_key_file: /home/vagrant/.ssh/id_rsa   

  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
              jenkins-agent-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: vagrant
