---
all:
  hosts:
    jenkins-master-01:
      ansible_host: 51.250.73.253
      ansible_ssh_private_key_file: /home/vagrant/.ssh/id_rsa
    #  ansible_port: 22
    jenkins-agent-01:
      ansible_host: 158.160.45.141
      ansible_ssh_private_key_file: /home/vagrant/.ssh/id_rsa   
 #  ansible_port: 22
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
              jenkins-agent-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: vagrant
