---
hosts:
    jenkins-master-01:
      ansible_host: 62.84.125.153
      ansible_ssh_private_key_file: /home/vagrant/.ssh/id_ed25519
    jenkins-agent-01:
      ansible_host: 84.252.131.2
      ansible_ssh_private_key_file: /home/vagrant/.ssh/id_ed25519
